# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170805_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrical',
            name='author',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='author',
        ),
        migrations.DeleteModel(
            name='Electrical',
        ),
        migrations.DeleteModel(
            name='Electronics',
        ),
    ]
